### ISSUE TITLE
panic: label value "inner-job-同\xe6\xad" is not valid UTF-8

### ISSUE THREAD

**Issue by shuzheng** [ncabatoff/process-exporter#239]
2022/07/29 06:42:32 Reading metrics from /host/proc based on "/var/process-exporter/config.yml"
level=info ts=2022-07-29T06:42:35.905Z caller=tls_config.go:195 msg="TLS is disabled." http2=false
panic: label value "inner-job-同\xe6\xad" is not valid UTF-8

goroutine 61 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/value.go:107
github.com/ncabatoff/process-exporter/collector.(*NamedProcessCollector).scrape(0xc0000cd360, 0xc000ae4000)
	/go/src/github.com/ncabatoff/process-exporter/collector/process_collector.go:318 +0x2791
github.com/ncabatoff/process-exporter/collector.(*NamedProcessCollector).start(0xc0000cd360)
	/go/src/github.com/ncabatoff/process-exporter/collector/process_collector.go:248 +0x48
created by github.com/ncabatoff/process-exporter/collector.NewProcessCollector
	/go/src/github.com/ncabatoff/process-exporter/collector/process_collector.go:206 +0x3cf

**Comment by fcecagno** [comment]
I'm hitting this issue, even though I'm using `-threads false`, so I wouldn't expect process-exporter to mess with thread names in the first place.
