### ISSUE TITLE
help！process_exporter Unable to start

### ISSUE THREAD

**Issue by trustnote-wang** [ncabatoff/process-exporter#265]
panic: label value "1-1-syslog采\xe9\x9b" is not valid UTF-8

goroutine 9 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
  /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/value.go:107
github.com/ncabatoff/process-exporter/collector.(*NamedProcessCollector).scrape(0xc000220320, 0xc00060e240)
  /home/runner/work/process-exporter/process-exporter/collector/process_collector.go:318 +0x2791
github.com/ncabatoff/process-exporter/collector.(*NamedProcessCollector).start(0xc000220320)
  /home/runner/work/process-exporter/process-exporter/collector/process_collector.go:248 +0x48
created by github.com/ncabatoff/process-exporter/collector.NewProcessCollector
  /home/runner/work/process-exporter/process-exporter/collector/process_collector.go:206 +0x3cf

**Comment by trustnote-wang** [comment]
Can someone help me? Thank you very much

**Comment by trustnote-wang** [comment]
hello, any body here?

**Comment by steinbrueckri** [comment]
@trustnote-wang can you provide some information about your System the version you are using and past also your config file? Without this information is impossible to help you at all. Also, see [writing-a-proper-github-issue](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f).
