### ISSUE TITLE
panic: label value "ODS_T_BUGT - \xe8\xa1" is not valid UTF-8

### ISSUE THREAD

**Issue by caihaihcao** [ncabatoff/process-exporter#323]
The process-exporter crashes after running for a while, and I would like to ask a professional to help me check this issue，Currently using version 0.8.4，The following are the relevant errors
Nov  8 04:00:35 cmsapp process-exporter[3371838]: panic: label value "ODS_T_BUGT - \xe8\xa1" is not valid UTF-8
Nov  8 04:00:35 cmsapp process-exporter[3371838]: goroutine 50 [running]:
Nov  8 04:00:35 cmsapp process-exporter[3371838]: github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
Nov  8 04:00:35 cmsapp process-exporter[3371838]: #011/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.19.0/prometheus/value.go:129
Nov  8 04:00:35 cmsapp process-exporter[3371838]: github.com/ncabatoff/process-exporter/collector.(*NamedProcessCollector).scrape(0xc00021c1e0, 0xc000b17180)
Nov  8 04:00:35 cmsapp process-exporter[3371838]: #011/home/runner/work/process-exporter/process-exporter/collector/process_collector.go:321 +0x1f91
Nov  8 04:00:35 cmsapp process-exporter[3371838]: github.com/ncabatoff/process-exporter/collector.(*NamedProcessCollector).start(...)
Nov  8 04:00:35 cmsapp process-exporter[3371838]: #011/home/runner/work/process-exporter/process-exporter/collector/process_collector.go:251
Nov  8 04:00:35 cmsapp process-exporter[3371838]: created by github.com/ncabatoff/process-exporter/collector.NewProcessCollector in goroutine 1
Nov  8 04:00:35 cmsapp process-exporter[3371838]: #011/home/runner/work/process-exporter/process-exporter/collector/process_collector.go:209 +0x40a

**Comment by caihaihcao** [comment]
This problem has been bothering me for a long time. I upgraded from version 0.7.10 to 0.8.4 but still haven't solved it. The content of config. yml is as follows
process_names:
     - name: "{{.Comm}}"
       cmdline:
       - '.+'
